### ISSUE TITLE
Ehfheatwaves installation error

### ISSUE THREAD

**Issue by GanarajDalal** [tammasloughran/ehfheatwaves#19]
While installing ehfheatwaves using command, pip  install git clone https://github.com/tammasloughran/ehfheatwaves 
Following error is coming 
 ERROR: Cannot unpack file C:\Users\ganar\AppData\Local\Temp\pip-unpack-i1w8q2wi\ehfheatwaves (downloaded from C:\Users\ganar\AppData\Local\Temp\pip-req-build-c7dk0vh6, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of C:\Users\ganar\AppData\Local\Temp\pip-req-build-c7dk0vh6

**Comment by tammasloughran** [comment]
Hi @GanarajDalal ,

`pip install git clone <url>` is not a valid pip install command.

You can either download the repository, change your current working dorectory to the repository and install with pip from there:

```sh
git clone https://github.com/tammasloughran/ehfheatwaves
cd ehfheatwaves
pip install .
```

Or if you really want to install directly from the URL then you shouldn't have the `git clone` in the install command. Instead you prepend the URL with `git+`

```sh
pip install git+https://github.com/tammasloughran/ehfheatwaves
```

Cheers,
Tam
