### ISSUE TITLE
related to excess heat factor  code

### ISSUE THREAD

**Issue by GanarajDalal** [tammasloughran/ehfheatwaves#20]
Following code is running on linux terminal,

ehfheatwaves -x"/home/ganaraj/Documents/data/Tmax_1951_2020_13Jan_ch.nc" -n"/home/ganaraj/Documents/data/Tmin_1951_2020_chunit.nc" -m"/home/ganaraj/Documents/data/Tmax_mask_1951_2020_13Jan_ch.nc" --vnamex=tmax --vnamen=tmin  --vnamem=mask  --vnamet=time --base=1951-2020  --dailyonly

And when I run tx90pc command I am getting following error
ehfheatwaves -x"/home/ganaraj/Documents/data/Tmax_1951_2020_13Jan_ch.nc" -n"/home/ganaraj/Documents/data/Tmin_1951_2020_chunit.nc" -m"/home/ganaraj/Documents/data/Tmax_mask_1951_2020_13Jan_ch.nc" --vnamex=tmax --vnamen=tmin  --vnamem=mask  --vnamet=time --base=1951-2020 --tx90pc
Traceback (most recent call last):
  File "/home/ganaraj/anaconda3/bin/ehfheatwaves", line 8, in <module>
    sys.exit(main())
  File "/home/ganaraj/anaconda3/lib/python3.9/site-packages/ehfheatwaves/ehfheatwaves.py", line 424, in main
    HWA_EHF, HWM_EHF, HWN_EHF, HWF_EHF, HWD_EHF, HWT_EHF = split_hemispheres(EHF, north,
  File "/home/ganaraj/anaconda3/lib/python3.9/site-packages/ehfheatwaves/ehfheatwaves.py", line 255, in split_hemispheres
    EHF_n = EHF[:,(mask[lats<=0]>0).sum():]
NameError: name 'mask' is not defined

**Comment by tammasloughran** [comment]
The output should be in the same directory as it is run in.

Looks like I introduced a bug recently when I refactored the code. I can fix it.

**Comment by tammasloughran** [comment]
The mask issue should be fixed. Please pull the latest version, install it and try running again.
```bash
cd ehfheatwaves
git pull https://github.com/tammasloughran/ehfheatwaves.git
pip install .
ehfheatwaves -x "/home/ganaraj/Documents/data/Tmax_1951_2020_13Jan_ch.nc" -n "/home/ganaraj/Documents/data/Tmin_1951_2020_chunit.nc" -m "/home/ganaraj/Documents/data/Tmax_mask_1951_2020_13Jan_ch.nc" --vnamex=tmax --vnamen=tmin --vnamem=mask --vnamet=time --base=1951-2020 --tx90pc
```

**Comment by tammasloughran** [comment]
Also, are you sure you want your base period (i.e. for the 90th percentile climatology that heatwaves are relative to) to be the entire data? I recommend using some standard base period in case you want to compare it to a different data set that might span a different period. The default is 1961-1990.
