### ISSUE TITLE
speedup quantile_zhang

### ISSUE THREAD

**Issue by mathause** [tammasloughran/ehfheatwaves#8]
You can speed up `quantile_zhang` by a factor of ~3 if you use `np.percentile` with an adjusted  `q`:

``` python
import numpy as np
from qtiler import quantile_zhang

def quantile_zhang_fast(x, q):
    
    n = x.shape[0]

    # adjust q such that np.percentile returns the same as quantile_zhang
    #  numpy uses (n -1); quantile_zhang uses (n + 1)
    q_adj = q * (n + 1.) / (n - 1.)
    #  numpy uses indices j and j+1; quantile_zhang uses j-1 and j
    q_adj -= 1. * 100./(n - 1)

    # ensure q_adj is in 0..100
    q_adj = np.clip(q_adj, 0., 100.)
    
    return np.percentile(x, q_adj, axis=0)
```

test a random field
``` python
z = np.random.randn(15*30*3, 72, 144)

Z = quantile_zhang(z, 90)
NZ = quantile_zhang_fast(z, 90)

# it's the same
np.allclose(Z, NZ)
```
time for execution
``` python
%timeit quantile_zhang(z, 90)
# 1 loop, best of 3: 562 ms per loop
%timeit quantile_zhang_fast(z, 90)
# 1 loop, best of 3: 188 ms per loop
```

test more systematically
```python
# length of the array from 10 to 10'000
for length in np.ceil(np.logspace(1, np.log10(10000), num=100)):
    x = np.random.randn(int(length))
    print(int(length))

    # quantiles from 0 to 100
    for q in range(0, 101):

        assert np.allclose(quantile_zhang_fast(x, q), quantile_zhang(x, q))
```

The relevant code is here:

[numpy](https://github.com/numpy/numpy/blob/v1.14.2/numpy/lib/function_base.py#L4336)

[quantile_zhang](https://github.com/tammasloughran/ehfheatwaves/blob/master/qtiler.py#L139)

**Comment by tammasloughran** [comment]
Hi Mathias

Wow! Thanks for this! I had no idea the numpy function was even equivalent.
I never really use this function, so I never bothered with trying to get it to run faster.
If you have already changed this yourself, you are welcome to make a pull request for it and I'll merge it.
Otherwise, I can change it when I get around to cleaning up the ehfheatwaves code - no promises when that will be though. 

Thanks again,

Tam

**Comment by tammasloughran** [comment]
I just implemented your function. Thanks mate! Much appreciated.

**Comment by mathause** [comment]
Cool you implemented this. However, you don't need to raise an error when q_adj is outside 0...100.

https://github.com/tammasloughran/ehfheatwaves/blob/master/qtiler.py#L203

The original `quantile_zhang` also clips them to the highest and lowest value - see the following lines

https://github.com/tammasloughran/ehfheatwaves/blob/master/qtiler.py#L163-L167

**Comment by tammasloughran** [comment]
Oooh, gotcha. I thought it was a bit risky but I'd already put a check in for crazy input q values.

637f397
